### ISSUE TITLE
Output Env Variable is not Marked as Secret

### ISSUE THREAD

**Issue by LanceMcCarthy** [cmancone/akeyless-action#2]
When running this action, both the output variable and env variable is not marked as a secret value. The has the side effect where the raw value of the secret is visible in every step after the action.

As an example, here's the output of a workflow that I have to dleete quickly:

![image](https://user-images.githubusercontent.com/3520532/187543274-ab042ae2-82d5-41c8-888b-c877a7b2858c.png)

Is there a way to mark these as secret? If not, I propose an input switch that lets you toggle the output as secrets.

Note: I am an author of several GitHub Actions myself (e.g., https://github.com/LanceMcCarthy/Action-AzureBlobUpload). I can't recall if you can mark a job output as secret, but I do know you can set the env var as secret.

**Comment by LanceMcCarthy** [comment]
Here are the resources I use when writing custom actions:

- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
- https://docs.github.com/en/actions/learn-github-actions/environment-variables

I do see that you can use the Actions toolkiit command to set a secret:

![image](https://user-images.githubusercontent.com/3520532/187546556-c2153a25-d074-4e71-9c11-82e3b9530416.png)

I think you should be able to apply the mask before setting it as an output and/or env var.

You may also be able to add a mask using the  `::add-mask::` prefix, but I'm not sure about this one. See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-log 

```
myVarToExport = "::add-mask::$MY_KEY_VALUE"
```

**Comment by cmancone** [comment]
Yeah, apparently I just forgot that detail while working on the secret export.  For the AWS login process, I used `setSecret`, but for the more generic secret export, I used `setOutput`.  I've updated all of them to use `setSecret`.

There's room for weirdness if you output a secret but *only* have it set to an environment variable, and not as an output, since it is the `setSecret` that applies the masking (I think), but that seems like a pretty minor edge case that isn't immediately on my list of concerns.

**Comment by cmancone** [comment]
Note that I bumped the version to 2.  v1 will still give you the old behavior.

**Comment by LanceMcCarthy** [comment]
Thanks for the fast turnaround!

**Comment by LanceMcCarthy** [comment]
Spoke too soon, I think we might need to re-open this. I just re-ran the job with both export options set to true. The name of the variable is a secret, but not the value 😮 

In the following screenshot, you can see the env variables loaded into the 2nd step. The var from the fetch-secrets step is in plain text (but the name of the var is masked)

![image](https://user-images.githubusercontent.com/3520532/187676580-743ad67a-2c8a-450f-9ac3-73a0491d4e50.png)


If you're not able to visit this again today, let me know. I can take a whack at it and will open a PR. I don't like complaining without offering useful suggestions or directly lend a hand in the code.

**Comment by LanceMcCarthy** [comment]
Hi Connor,

I found an older Action that masks the secrets first, then sets the value to output and variables. Here is the exact helper method that will everything for you in one shot: https://github.com/Azure/get-keyvault-secrets/blob/c2b531e47fab4ca7cd8df09d44a65256651bf46e/src/KeyVaultHelper.ts#L106-L114 

I have already forked the repo and fixed it up locally, I will open a PR for you so that you can just verify it works and merge in for v2.1 (or v3, whatever is easier for you to release).

**Comment by LanceMcCarthy** [comment]
Phew, okay, I finally got it working as intended and opened a pull request for you => https://github.com/cmancone/akeyless-action/pull/5
